#Details
name=input("Enter the name:")
name1=name.upper()
age=int(input("Enter your age:"))
address=input("Enter the address:")
height=float(input("Enter the height:"))
Country=input("Enter the country:")

print( "\nYour Details:\n")
print(f"Hello, {name1}\n")
print(f"You are {age} years old\n")
print(f"Your address is {address}\n")
print(f"Your height is {height:.2f}\n")              
print(f"Your country is {Country}\n")              
print(f"your Nickname is {name1[:2] + name1[-2:]}\n")
